typography_spectrum: 0.726351
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.840116
  lightness: 0.722973
  rhythmicContrast: 0.828828
  saturation: 0.75
opengraph: {}
layout_spectrum: 0.176801
analytics: {}
name: amazing-indonesia
cta: {}
navigation:
  - name: Our smile
    id: 12029a06-3d32-415a-a5d2-e39474f3d43b
    type: content
description: See our smile
purpose: {}
